name: CI

on:
  push:
    branches:
      - feature/** 
  
jobs:
  terraform:
    name: Terraform Lint & Test
    runs-on: ubuntu-latest
    permissions:
      id-token: write   
      contents: read    

    steps:
      - name: チェックアウト
        uses: actions/checkout@9f698171ed81b15d1823a05fc7211befd50c8ae0 # v6.0.3


      - name: Terraformセットアップ
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: "1.14.8" 

      - name: AWS認証
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0

        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1

      - name: Terraform Init
        run: terraform init
        working-directory: modules

      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: modules

      - name: Terraform Validate
        run: terraform validate
        working-directory: modules

      - name: Terraform Test
        run: terraform test
        working-directory: modules
        env:
          TF_VAR_key_name: ${{ secrets.TF_VAR_KEY_NAME }}
          TF_VAR_my_ip: ${{ secrets.TF_VAR_MY_IP }}
          TF_VAR_db_username: ${{ secrets.TF_VAR_DB_USERNAME }}
          TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}
          TF_VAR_alert_email: ${{ secrets.TF_VAR_ALERT_EMAIL }}
          TF_VAR_env: ${{ secrets.TF_VAR_ENV }}

      